### ISSUE TITLE
Making jo.1

### ISSUE THREAD

**Issue by jpmens** [caius/homebrew-jo#1]
Thanks, Caius, for doing this. If I read the ruby recipe correctly, you create the man page with `make jo.1`; should we omit this as it will work only if people have _pandoc_ installed? (The jo repo provides an up-to-date `jo.1`.)

**Comment by caius** [comment]
@jpmens ah, good point, hadn't thought of that. I was just taking `make all` and omitting the Readme as that didn't need installing. I'll change this to just install the `jo.1` from the git repo instead, thanks
