### ISSUE TITLE
Jo releases

### ISSUE THREAD

**Issue by jpmens** [caius/homebrew-jo#3]
I've added _autotools_ support to _jo_, and I'll be publishing releases [here](https://github.com/jpmens/jo/releases/). May I ask you to change the your formula to do the `./configure;make` incantation? 

I hope I won't have to trouble you again...

**Comment by caius** [comment]
Awesome, that'll make it easier to upstream (homebrew master doesn't like HEAD only formula). I was going to ask once the tool had stabilised a little if you were going to cut releases. :grin:

**Comment by jpmens** [comment]
Thanks for doing this, and thanks for adding me. If you fix the formula, I'll be sure to add to it if need be in the future.

**Comment by caius** [comment]
Fixed by #4
